name: build push and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: Aws creds config
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }} # OIDC
      - name: Login to ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      
